# https://taskfile.dev
version: '3'
tasks:
  version:
    cmds:
    - docker version
    - docker-compose version
    
  setup:
    desc: setup lcoal docker-env
    cmds:
    - task: os:install-desktop

includes:
  os: ./Taskfile_{{OS}}.yml